### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by Alex-Matveenko** [yuyudhn/TLDHunt#1]
Greetings. Thank you for your project, it is a very useful tool. I would like to point out that the project has an unaccounted for scenario in the line `result=$(whois "$domain" 2>/dev/null | grep -i "Name Server")`, only since 2013 the basic data registration in whois is by template, domains registered before that date may not contain Name Server in the response. After testing on every possible domain name I could think of, I determined the pattern that has more matches result=$(whois "$domain" 2>/dev/null | grep -i "Name Server\|nserver\|nameservers\|status: active"). If you are interested, you can fix this part in your application and it will give more accurate information. Thanks again for your work!

**Comment by yuyudhn** [comment]
cool. thanks for the suggestion. updated!
