### ISSUE TITLE
inaccurate ??

### ISSUE THREAD

**Issue by changchichung** [yuyudhn/TLDHunt#4]
for keyword: "the" , I run the command below

````
./tldhunt.sh -k the -E /tmp/tlds.txt
```

here is a part of screen messages 
```
[taken] - the.site
[avail] - the.sale
[avail] - the.shoes
[avail] - the.soccer
[avail] - the.sarl
[avail] - the.ski
[avail] - the.republican
[avail] - the.social
[avail] - the.singles
[avail] - the.report
[avail] - the.reviews
[avail] - the.shopping
[avail] - the.restaurant
[avail] - the.schule
[avail] - the.services
[avail] - the.shiksha
[avail] - the.soy
[avail] - the.systems
[avail] - the.tienda
[avail] - the.solar
[avail] - the.supply
[avail] - the.sucks
[taken] - the.surf
```
as you can see , "the.systems" domain should be available. but it's not
```
$ whois the.systems
Domain Name: the.systems
Registry Domain ID: 27db9f1cf53f4c24b62a036784feede6-DONUTS
Registrar WHOIS Server: whois.porkbun.com
Registrar URL: http://porkbun.com
Updated Date: 2022-10-08T12:43:09Z
Creation Date: 2021-08-20T23:34:40Z
Registry Expiry Date: 2023-08-20T23:34:40Z
Registrar: Porkbun LLC
Registrar IANA ID: 1861
Registrar Abuse Contact Email: abuse@porkbun.com
Registrar Abuse Contact Phone: +1.5038508351
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Registry Registrant ID: REDACTED FOR PRIVACY
Registrant Name: REDACTED FOR PRIVACY
```

Could it be that some of the conditional criteria are problematic?

**Comment by lookfirst** [comment]
`result=$(whois "$domain" 2>/dev/null | grep -i "Name Server\|nserver\|nameservers\|status: active")`

Sadly, this tool really isn't coded up well. That's the only check that it does. The output from whois is pretty endless in the variations of what it returns and this tool really doesn't cover all cases at all.

**Comment by yuyudhn** [comment]
> `result=$(whois "$domain" 2>/dev/null | grep -i "Name Server\|nserver\|nameservers\|status: active")`
> 
> Sadly, this tool really isn't coded up well. That's the only check that it does. The output from whois is pretty endless in the variations of what it returns and this tool really doesn't cover all cases at all.

that's why i publish it on Github. So community can make this tool better.

**Comment by yuyudhn** [comment]
> for keyword: "the" , I run the command below
> 
> ```
> ./tldhunt.sh -k the -E /tmp/tlds.txt
> ```
> 
> here is a part of screen messages 
> ```
> [taken] - the.site
> [avail] - the.sale
> [avail] - the.shoes
> [avail] - the.soccer
> [avail] - the.sarl
> [avail] - the.ski
> [avail] - the.republican
> [avail] - the.social
> [avail] - the.singles
> [avail] - the.report
> [avail] - the.reviews
> [avail] - the.shopping
> [avail] - the.restaurant
> [avail] - the.schule
> [avail] - the.services
> [avail] - the.shiksha
> [avail] - the.soy
> [avail] - the.systems
> [avail] - the.tienda
> [avail] - the.solar
> [avail] - the.supply
> [avail] - the.sucks
> [taken] - the.surf
> ```
> as you can see , "the.systems" domain should be available. but it's not
> ```
> $ whois the.systems
> Domain Name: the.systems
> Registry Domain ID: 27db9f1cf53f4c24b62a036784feede6-DONUTS
> Registrar WHOIS Server: whois.porkbun.com
> Registrar URL: http://porkbun.com
> Updated Date: 2022-10-08T12:43:09Z
> Creation Date: 2021-08-20T23:34:40Z
> Registry Expiry Date: 2023-08-20T23:34:40Z
> Registrar: Porkbun LLC
> Registrar IANA ID: 1861
> Registrar Abuse Contact Email: abuse@porkbun.com
> Registrar Abuse Contact Phone: +1.5038508351
> Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
> Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
> Registry Registrant ID: REDACTED FOR PRIVACY
> Registrant Name: REDACTED FOR PRIVACY
> ```
> 
> Could it be that some of the conditional criteria are problematic?
> ```
in my side, the tool said the.systems is taken.
